---
title: "A brief tutorial on runing Maxent in R"
author: "Xiao Feng, Cassondra Walker, Fikirte Gebresenbet"
date: "July 4, 2017"
output: 
  pdf_document: 
    toc: true
    toc_depth: 3
---

```{r}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

##1. setup the working environment  
###1.1 load packages  
```{r setup,message=FALSE}
library(dismo)
library(raster)
library(knitr)
#knitr::opts_knit$set(root.dir = 'd:/projects/2017_7_workshop_enm_R')
```

###1.2 set up the Maxent path  
```{r maxent, eval=FALSE, echo=TRUE}
# download maxent.jar 3.3.3k, and place the file in the desired folder
a <- 1 # wb for binary file, otherwise maxent.jar can not executewb for binary file, otherwise maxent.jar can not executewb for binary file, otherwise maxent.jar can not executewb for binary file, otherwise maxent.jar can not executewb for binary file, otherwise maxent.jar can not execute
# also note that both R and Java need to be the same bit (either 32 or 64) to be compatible to run

#options( java.parameters = c("-Xss2560k", "-Xmx2g") ) ## increase memory size of the JVM, this code may prevent memory issues of Maxent.jar

```